### PR TITLE
Compatibility with Python 3.8+

### PR DESCRIPTION
**Pull request by mariahjrogers**
Several `singer-io` community taps use this framework package (eg. [singer-io/tap-chargebee](https://github.com/singer-io/tap-chargebee), my use case), and I traced the limiting factor for making those taps compatible with Python versions 3.8, 3.9 and 3.10 back to this package's dependency pins.

These changes were tested with my team's fork of `tap-chargebee` on a machine running with Python 3.10.10 along with the tap's other dependencies also upgraded to Python 3.10 compatible versions.

### CODE REVIEW

**Comment by gwenwindflower** [comment]
hey mariah, had @dbeatty10 on the DX team look at this and in general it seems great.

there's a set of issues with this repo though: lacking CI, contribution instructions or a README, release instructions, etc -- none of that is on you, but would be necessary if we were going to actively maintain this repo as dbt Labs now.

which leads me to this: would you and/or Cypress be interested in forking and taking over this repo if you use it? if so, you're very welcome to. let me know what general questions or vibes you have to that at first glance, thanks!

**Comment by mariahjrogers** [comment]
@gwenwindflower generally I do not think Cypress would be interested in maintaining this. It is sort of a twice-removed situation here, that we depend on a tap, which depends on this package. But we are not actively contributing to said tap; only noticed the issue.

(I did replace our dependency on `tap-framework` with my fork of this repo, but it seems wishy washy to our infra team to have it depend on my personal fork)

**Comment by gwenwindflower** [comment]
ahh i see now! all good. could you link me the tap? i wonder if we could either get that tap dev to remove their dependency or take ownership of this repo. to be clear we can get these changes merged, i just want to figure out a way forward as there's no capacity internally to properly support this repo at this point that i can see.

**Comment by mariahjrogers** [comment]
@gwenwindflower its [tap-chargebee](https://github.com/singer-io/tap-chargebee)!

**Comment by epapineau** [comment]
Hey @gwenwindflower where did this land? I'd love to avoid having to rollback my local python version if possible 🙏🏻

**Comment by dbeatty10** [comment]
I'd feel fine about just merging this PR as-is.

It sounds like the current dependencies don't work with Python 3.8, and Python 3.7 will be [end-of-life](https://devguide.python.org/versions/) in less than 60 days from now (2023-06-27).

**Comment by epapineau** [comment]
Many thanks @dbeatty10, @gwenwindflower, & @mariahjrogers 🙇🏻

**Pull request merged**
