### PR TITLE
Bump singer-python from <5.2.0 to <5.5.0

### PR DESCRIPTION
**Pull request by jtcohen6**
* `singer-python>=5.4.0` includes support for `patternProperties` in JSON schemas: https://github.com/singer-io/singer-python/pull/92

### CODE REVIEW

**Comment by bthomson22** [comment]
cc @epapineau as this aligns with your need for `singer-python==5.4.0`

**Comment by epapineau** [comment]
@jtcohen6 @cmcarthur and / or @drewbanin any objections on merging this change in? 🙏🏻

**Comment by cmcarthur** [comment]
@epapineau were you able to test this change in any way to make sure it doesn't break tap-framework?

the change itself looks okay

**Comment by epapineau** [comment]
@cmcarthur I am successfully running a tap using a local `tap-framework` `setup.py` as:
```
          'singer-python>=5.4.0,<5.5.0',
```

I specifically need [this](https://github.com/singer-io/singer-python/blame/0c066de21111d8572425083b4a8792d193c80af1/singer/transform.py#L297) change to enable ingesting objects.

**Comment by bthomson22** [comment]
@cmcarthur @drewbanin we tested this locally on several of our taps and everything worked as expected. If we need to expand testing beyond this we will need some guidance from the both/one of you. I do see that there are several dependencies on this package built by other orgs.

Of note - from an internal perspective, our taps are largely pinned to a specific version of `tap-framework`, not a range, so internally we will be good to go. We'll update this following the merge, but there are no immediate red flags.

**Review by cmcarthur — APPROVED** [review]

**Comment by cmcarthur** [comment]
approved from my end.

**Comment by epapineau** [comment]
@cmcarthur can we assist with getting the [release on pypi ](https://pypi.org/project/tap-framework/#history)?

**Pull request merged**
